// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using peluqueria.reservaciones.Infraestructura.Persistencia;

#nullable disable

namespace peluqueria.reservaciones.Migrations
{
    [DbContext(typeof(ReservacionesDbContext))]
    [Migration("20251129173430_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.BloqueoRangoDiasLibres", b =>
                {
                    b.Property<int>("EstilistaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicioBloqueo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFinBloqueo")
                        .HasColumnType("datetime2");

                    b.HasKey("EstilistaId", "FechaInicioBloqueo");

                    b.ToTable("BloqueoRangoDias");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.Cliente", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identificacion");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.DescansoFijo", b =>
                {
                    b.Property<int>("EstilistaId")
                        .HasColumnType("int");

                    b.HasKey("EstilistaId");

                    b.ToTable("DescansoFijo");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.Estilista", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estilistas");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.HorarioBase", b =>
                {
                    b.Property<int>("EstilistaId")
                        .HasColumnType("int");

                    b.HasKey("EstilistaId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.Reservacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstilistaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("TiempoAtencion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteIdentificacion");

                    b.HasIndex("EstilistaId");

                    b.HasIndex("ServicioId");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.DescansoFijo", b =>
                {
                    b.OwnsMany("peluqueria.reservaciones.Core.Dominio.DiaHorario", "DescansosFijos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DescansoFijoEstilistaId")
                                .HasColumnType("int");

                            b1.Property<int>("DiaSemana")
                                .HasColumnType("int");

                            b1.Property<bool>("EsLaborable")
                                .HasColumnType("bit");

                            b1.Property<TimeSpan>("HoraFin")
                                .HasColumnType("time");

                            b1.Property<TimeSpan>("HoraInicio")
                                .HasColumnType("time");

                            b1.HasKey("Id");

                            b1.HasIndex("DescansoFijoEstilistaId");

                            b1.ToTable("DescansoFijo_Dias", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DescansoFijoEstilistaId");
                        });

                    b.Navigation("DescansosFijos");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.HorarioBase", b =>
                {
                    b.OwnsMany("peluqueria.reservaciones.Core.Dominio.DiaHorario", "HorariosSemanales", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DiaSemana")
                                .HasColumnType("int");

                            b1.Property<bool>("EsLaborable")
                                .HasColumnType("bit");

                            b1.Property<TimeSpan>("HoraFin")
                                .HasColumnType("time");

                            b1.Property<TimeSpan>("HoraInicio")
                                .HasColumnType("time");

                            b1.Property<int>("HorarioBaseEstilistaId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("HorarioBaseEstilistaId");

                            b1.ToTable("HorarioBase_Dias", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HorarioBaseEstilistaId");
                        });

                    b.Navigation("HorariosSemanales");
                });

            modelBuilder.Entity("peluqueria.reservaciones.Core.Dominio.Reservacion", b =>
                {
                    b.HasOne("peluqueria.reservaciones.Core.Dominio.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("peluqueria.reservaciones.Core.Dominio.Estilista", "Estilista")
                        .WithMany()
                        .HasForeignKey("EstilistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("peluqueria.reservaciones.Core.Dominio.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estilista");

                    b.Navigation("Servicio");
                });
#pragma warning restore 612, 618
        }
    }
}
