// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peluqueria.Infrastructure.Data;

#nullable disable

namespace Peluqueria.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251124232241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d17abceb-8c0b-454e-b296-883bc029d82b",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "e10b1a03-9f2d-45f8-8f8e-20bc8b67b7e3",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        },
                        new
                        {
                            Id = "a20b1a03-9f2d-45f8-8f8e-20bc8b67b7e3",
                            Name = "Estilista",
                            NormalizedName = "ESTILISTA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            RoleId = "d17abceb-8c0b-454e-b296-883bc029d82b"
                        },
                        new
                        {
                            UserId = "b7e289d1-d21a-4c9f-8d7e-00bd9344e575",
                            RoleId = "a20b1a03-9f2d-45f8-8f8e-20bc8b67b7e3"
                        },
                        new
                        {
                            UserId = "c7e289d1-d21a-4c9f-8d7e-00bd9344e575",
                            RoleId = "e10b1a03-9f2d-45f8-8f8e-20bc8b67b7e3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.BloqueoDescansoFijoDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("EstilistaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFinDescanso")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicioDescanso")
                        .HasColumnType("time");

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstilistaId");

                    b.ToTable("BloqueosDescansoFijoDiario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaSemana = 1,
                            EstilistaId = 2,
                            HoraFinDescanso = new TimeSpan(0, 14, 0, 0, 0),
                            HoraInicioDescanso = new TimeSpan(0, 13, 0, 0, 0),
                            Razon = "Almuerzo"
                        },
                        new
                        {
                            Id = 2,
                            DiaSemana = 3,
                            EstilistaId = 2,
                            HoraFinDescanso = new TimeSpan(0, 14, 0, 0, 0),
                            HoraInicioDescanso = new TimeSpan(0, 13, 0, 0, 0),
                            Razon = "Almuerzo"
                        },
                        new
                        {
                            Id = 3,
                            DiaSemana = 5,
                            EstilistaId = 2,
                            HoraFinDescanso = new TimeSpan(0, 14, 0, 0, 0),
                            HoraInicioDescanso = new TimeSpan(0, 13, 0, 0, 0),
                            Razon = "Almuerzo"
                        });
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.BloqueoRangoDiasLibres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstilistaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinBloqueo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioBloqueo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstilistaId");

                    b.ToTable("BloqueosRangoDiasLibres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstilistaId = 2,
                            FechaFinBloqueo = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicioBloqueo = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Razon = "Vacaciones"
                        });
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstaActiva = true,
                            Nombre = "Cortes de Cabello"
                        },
                        new
                        {
                            Id = 2,
                            EstaActiva = true,
                            Nombre = "Tratamientos Capilares"
                        },
                        new
                        {
                            Id = 3,
                            EstaActiva = true,
                            Nombre = "Manicura y Pedicura"
                        },
                        new
                        {
                            Id = 4,
                            EstaActiva = true,
                            Nombre = "Otra"
                        });
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.Estilista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estilistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstaActivo = true,
                            IdentityId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            Imagen = "",
                            NombreCompleto = "Administrador Principal",
                            Telefono = "3001234567"
                        },
                        new
                        {
                            Id = 2,
                            EstaActivo = true,
                            IdentityId = "b7e289d1-d21a-4c9f-8d7e-00bd9344e575",
                            Imagen = "",
                            NombreCompleto = "Laura Valencia",
                            Telefono = "3001234568"
                        });
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.EstilistaServicio", b =>
                {
                    b.Property<int>("EstilistaId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("EstilistaId", "ServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("EstilistaServicios");

                    b.HasData(
                        new
                        {
                            EstilistaId = 1,
                            ServicioId = 1
                        },
                        new
                        {
                            EstilistaId = 1,
                            ServicioId = 2
                        },
                        new
                        {
                            EstilistaId = 1,
                            ServicioId = 3
                        },
                        new
                        {
                            EstilistaId = 2,
                            ServicioId = 1
                        },
                        new
                        {
                            EstilistaId = 2,
                            ServicioId = 4
                        });
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.HorarioSemanalBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<bool>("EsLaborable")
                        .HasColumnType("bit");

                    b.Property<int>("EstilistaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFinJornada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicioJornada")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EstilistaId");

                    b.ToTable("HorariosSemanalBase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaSemana = 1,
                            EsLaborable = true,
                            EstilistaId = 2,
                            HoraFinJornada = new TimeSpan(0, 18, 0, 0, 0),
                            HoraInicioJornada = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DiaSemana = 3,
                            EsLaborable = true,
                            EstilistaId = 2,
                            HoraFinJornada = new TimeSpan(0, 18, 0, 0, 0),
                            HoraInicioJornada = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DiaSemana = 5,
                            EsLaborable = true,
                            EstilistaId = 2,
                            HoraFinJornada = new TimeSpan(0, 18, 0, 0, 0),
                            HoraInicioJornada = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.ParametroSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BufferMinutos")
                        .HasColumnType("int");

                    b.Property<int>("DuracionMinimaServicioMinutos")
                        .HasColumnType("int");

                    b.Property<int>("ToleranciaLlegadaMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParametrosSistema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BufferMinutos = 5,
                            DuracionMinimaServicioMinutos = 45,
                            ToleranciaLlegadaMinutos = 10
                        });
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Un corte clásico...",
                            Disponible = true,
                            DuracionMinutos = 60,
                            FechaCreacion = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://localhost:7274/images/bobCut.png",
                            Nombre = "Corte Estilo Bob",
                            Precio = 50000m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Tratamiento keratina...",
                            Disponible = true,
                            DuracionMinutos = 90,
                            FechaCreacion = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://localhost:7274/images/hidratacion.jpg",
                            Nombre = "Hidratación Profunda",
                            Precio = 80000m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descripcion = "Experiencia relajante...",
                            Disponible = true,
                            DuracionMinutos = 75,
                            FechaCreacion = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://localhost:7274/images/manicura.jpg",
                            Nombre = "Manicura SPA Completa",
                            Precio = 80000m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "Corte clásico...",
                            Disponible = true,
                            DuracionMinutos = 45,
                            FechaCreacion = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagen = "https://localhost:7274/images/manCut.png",
                            Nombre = "Corte para hombre",
                            Precio = 30000m
                        });
                });

            modelBuilder.Entity("Peluqueria.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Email = "admin@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Administrador Principal",
                            NormalizedEmail = "ADMIN@TEST.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAELE7EUiQXrw+aCro/sc0YrgueeqB+qFkaQ5MXg9oomqzhesiq9XJxqeYYXaUom1slA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00000000-0000-0000-0000-000000000000",
                            Telefono = "3001234567",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "b7e289d1-d21a-4c9f-8d7e-00bd9344e575",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9769f6ea-d3b1-4734-b2c3-60e854c2cfe6",
                            Email = "laura.e@pelu.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Laura Valencia",
                            NormalizedEmail = "LAURA.E@PELU.COM",
                            NormalizedUserName = "LAURA.E",
                            PasswordHash = "AQAAAAIAAYagAAAAEBfk5VEqndwuGJTJJQUGONX9YEUaGQ2CwoC/1C9W9AeUxtfWq2963cu1/pBnyfHfKw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0ff912a-acd1-4574-9782-45529ffd1eda",
                            Telefono = "3001234568",
                            TwoFactorEnabled = false,
                            UserName = "laura.e"
                        },
                        new
                        {
                            Id = "c7e289d1-d21a-4c9f-8d7e-00bd9344e575",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe1e8649-edca-478d-a35e-2ce3a50ead90",
                            Email = "juan.c@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NombreCompleto = "Juan Cliente",
                            NormalizedEmail = "JUAN.C@MAIL.COM",
                            NormalizedUserName = "JUAN.C",
                            PasswordHash = "AQAAAAIAAYagAAAAENDiwYDXqNGLalxbCNuRjtAmMypgJxqE/R/bXHGdy6VhFaV6Ii5jjgGZ2t4W6zylew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6e020fbf-665b-4bcb-aea3-914a8e6bded0",
                            Telefono = "3109876543",
                            TwoFactorEnabled = false,
                            UserName = "juan.c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Peluqueria.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Peluqueria.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peluqueria.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Peluqueria.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.BloqueoDescansoFijoDiario", b =>
                {
                    b.HasOne("Peluqueria.Domain.Entities.Estilista", "Estilista")
                        .WithMany("BloqueosDescansoFijoDiario")
                        .HasForeignKey("EstilistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estilista");
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.BloqueoRangoDiasLibres", b =>
                {
                    b.HasOne("Peluqueria.Domain.Entities.Estilista", "Estilista")
                        .WithMany("BloqueosRangoDiasLibres")
                        .HasForeignKey("EstilistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estilista");
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.EstilistaServicio", b =>
                {
                    b.HasOne("Peluqueria.Domain.Entities.Estilista", "Estilista")
                        .WithMany("ServiciosAsociados")
                        .HasForeignKey("EstilistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peluqueria.Domain.Entities.Servicio", "Servicio")
                        .WithMany("EstilistasAsociados")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estilista");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.HorarioSemanalBase", b =>
                {
                    b.HasOne("Peluqueria.Domain.Entities.Estilista", "Estilista")
                        .WithMany("HorariosBase")
                        .HasForeignKey("EstilistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estilista");
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("Peluqueria.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.Estilista", b =>
                {
                    b.Navigation("BloqueosDescansoFijoDiario");

                    b.Navigation("BloqueosRangoDiasLibres");

                    b.Navigation("HorariosBase");

                    b.Navigation("ServiciosAsociados");
                });

            modelBuilder.Entity("Peluqueria.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("EstilistasAsociados");
                });
#pragma warning restore 612, 618
        }
    }
}
